# Generated by Django 5.2.4 on 2025-07-16 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_alter_employee_hire_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("Q1", "1분기"),
                            ("Q2", "2분기"),
                            ("Q3", "3분기"),
                            ("Q4", "4분기"),
                            ("HALF1", "상반기"),
                            ("HALF2", "하반기"),
                            ("ANNUAL", "연간"),
                        ],
                        max_length=10,
                        verbose_name="평가기간 타입",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="활성화"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "계획중"),
                            ("ONGOING", "진행중"),
                            ("COMPLETED", "완료"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "평가기간",
                "verbose_name_plural": "평가기간",
                "ordering": ["-year", "period_type"],
                "unique_together": {("year", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="ContributionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_achievement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="종합달성률(%)",
                    ),
                ),
                (
                    "contribution_score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="기여도 점수",
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="달성여부"),
                ),
                (
                    "evaluated_date",
                    models.DateField(blank=True, null=True, verbose_name="평가일"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="평가의견")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_evaluations",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_evaluations_given",
                        to="employees.employee",
                        verbose_name="평가자",
                    ),
                ),
                (
                    "evaluation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationperiod",
                        verbose_name="평가기간",
                    ),
                ),
            ],
            options={
                "verbose_name": "기여도 평가",
                "verbose_name_plural": "기여도 평가",
                "unique_together": {("employee", "evaluation_period")},
            },
        ),
        migrations.CreateModel(
            name="ExpertiseEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="요구 레벨",
                    ),
                ),
                (
                    "strategic_contribution",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="전략적 기여",
                    ),
                ),
                (
                    "interactive_contribution",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="상호작용 기여",
                    ),
                ),
                (
                    "technical_expertise",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="기술 전문성",
                    ),
                ),
                (
                    "business_understanding",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="비즈니스 이해",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="종합점수"
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="달성여부"),
                ),
                (
                    "evaluated_date",
                    models.DateField(blank=True, null=True, verbose_name="평가일"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="평가의견")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_evaluations",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "evaluation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationperiod",
                        verbose_name="평가기간",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expertise_evaluations_given",
                        to="employees.employee",
                        verbose_name="평가자",
                    ),
                ),
            ],
            options={
                "verbose_name": "전문성 평가",
                "verbose_name_plural": "전문성 평가",
                "unique_together": {("employee", "evaluation_period")},
            },
        ),
        migrations.CreateModel(
            name="ImpactEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_focus",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="고객중심",
                    ),
                ),
                (
                    "collaboration",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="협업",
                    ),
                ),
                (
                    "innovation",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="혁신",
                    ),
                ),
                (
                    "team_leadership",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="팀 리더십",
                    ),
                ),
                (
                    "organizational_impact",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="조직 영향력",
                    ),
                ),
                (
                    "external_networking",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="대외 네트워킹",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="종합점수"
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="달성여부"),
                ),
                (
                    "evaluated_date",
                    models.DateField(blank=True, null=True, verbose_name="평가일"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="평가의견")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_evaluations",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "evaluation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationperiod",
                        verbose_name="평가기간",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impact_evaluations_given",
                        to="employees.employee",
                        verbose_name="평가자",
                    ),
                ),
            ],
            options={
                "verbose_name": "영향력 평가",
                "verbose_name_plural": "영향력 평가",
                "unique_together": {("employee", "evaluation_period")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="과제명")),
                ("description", models.TextField(blank=True, verbose_name="과제설명")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="비중(%)",
                    ),
                ),
                (
                    "contribution_method",
                    models.CharField(
                        choices=[("리딩", "리딩"), ("지원", "지원"), ("공동", "공동")],
                        default="리딩",
                        max_length=20,
                        verbose_name="기여방식",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "target_unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="실적값",
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="달성률(%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "계획"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "evaluation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationperiod",
                        verbose_name="평가기간",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-weight", "title"],
            },
        ),
        migrations.CreateModel(
            name="ComprehensiveEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_achieved",
                    models.BooleanField(default=False, verbose_name="기여도 달성"),
                ),
                (
                    "expertise_achieved",
                    models.BooleanField(default=False, verbose_name="전문성 달성"),
                ),
                (
                    "impact_achieved",
                    models.BooleanField(default=False, verbose_name="영향력 달성"),
                ),
                (
                    "manager_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S등급"),
                            ("A+", "A+등급"),
                            ("A", "A등급"),
                            ("B+", "B+등급"),
                            ("B", "B등급"),
                            ("C", "C등급"),
                            ("D", "D등급"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="1차 평가등급",
                    ),
                ),
                (
                    "manager_comments",
                    models.TextField(blank=True, verbose_name="1차 평가의견"),
                ),
                (
                    "manager_evaluated_date",
                    models.DateField(blank=True, null=True, verbose_name="1차 평가일"),
                ),
                (
                    "final_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S등급"),
                            ("A+", "A+등급"),
                            ("A", "A등급"),
                            ("B+", "B+등급"),
                            ("B", "B등급"),
                            ("C", "C등급"),
                            ("D", "D등급"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="최종등급",
                    ),
                ),
                (
                    "calibration_comments",
                    models.TextField(blank=True, verbose_name="조정의견"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUBMITTED", "제출완료"),
                            ("IN_REVIEW", "검토중"),
                            ("COMPLETED", "확정"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprehensive_evaluations",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_as_manager",
                        to="employees.employee",
                        verbose_name="1차 평가자",
                    ),
                ),
                (
                    "contribution_evaluation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluations.contributionevaluation",
                        verbose_name="기여도 평가",
                    ),
                ),
                (
                    "evaluation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationperiod",
                        verbose_name="평가기간",
                    ),
                ),
                (
                    "expertise_evaluation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluations.expertiseevaluation",
                        verbose_name="전문성 평가",
                    ),
                ),
                (
                    "impact_evaluation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluations.impactevaluation",
                        verbose_name="영향력 평가",
                    ),
                ),
            ],
            options={
                "verbose_name": "종합평가",
                "verbose_name_plural": "종합평가",
                "ordering": ["-evaluation_period__year", "employee__name"],
                "unique_together": {("employee", "evaluation_period")},
            },
        ),
    ]
