# Generated by Django 5.2.4 on 2025-07-16 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertiseevaluation",
            name="business_acumen",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="비즈니스 감각",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="continuous_learning",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="지속적 학습",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="creative_solution",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="창의적 해결방안 제시",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="cross_functional",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="크로스펑셔널 협업",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="expertise_focus",
            field=models.CharField(
                choices=[
                    ("hard_skill", "Hard Skill Focused"),
                    ("balanced", "Balanced"),
                ],
                default="balanced",
                max_length=20,
                verbose_name="전문성 초점",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="industry_trend",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="산업 트렌드 파악",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="knowledge_sharing",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="지식 공유",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="mentoring",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="멘토링",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="process_improvement",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="프로세스 개선",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="strategic_thinking",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="전략적 사고",
            ),
        ),
        migrations.AddField(
            model_name="expertiseevaluation",
            name="technical_innovation",
            field=models.IntegerField(
                default=2,
                help_text="1: 이해, 2: 적용, 3: 자문, 4: 창의",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="기술적 혁신",
            ),
        ),
        migrations.AddField(
            model_name="impactevaluation",
            name="core_values_practice",
            field=models.CharField(
                choices=[
                    ("exemplary_values", "핵심가치 모범 실천"),
                    ("limited_values", "핵심가치 제한적 실천"),
                ],
                default="limited_values",
                max_length=20,
                verbose_name="핵심가치 실천",
            ),
        ),
        migrations.AddField(
            model_name="impactevaluation",
            name="impact_scope",
            field=models.CharField(
                choices=[
                    ("market", "조직외"),
                    ("corp", "조직간"),
                    ("org", "조직내"),
                    ("individual", "개인간"),
                ],
                default="org",
                max_length=20,
                verbose_name="영향력 범위",
            ),
        ),
        migrations.AddField(
            model_name="impactevaluation",
            name="leadership_demonstration",
            field=models.CharField(
                choices=[
                    ("exemplary_leadership", "리더십 모범 발휘"),
                    ("limited_leadership", "리더십 제한적 발휘"),
                ],
                default="limited_leadership",
                max_length=20,
                verbose_name="리더십 발휘",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="contribution_scope",
            field=models.CharField(
                choices=[
                    ("strategic", "전략적"),
                    ("mutual", "상호적"),
                    ("independent", "독립적"),
                    ("dependent", "의존적"),
                ],
                default="independent",
                max_length=20,
                verbose_name="기여범위",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="contribution_method",
            field=models.CharField(
                choices=[
                    ("directing", "총괄"),
                    ("leading", "리딩"),
                    ("individual", "실무"),
                    ("support", "지원"),
                ],
                default="leading",
                max_length=20,
                verbose_name="기여방식",
            ),
        ),
    ]
