# Generated by Django 5.2.4 on 2025-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_growthlevel_growthlevelrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthlevel',
            name='min_score_requirement',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='최소 점수 요구사항'),
        ),
        migrations.AddField(
            model_name='growthlevel',
            name='consecutive_achievements_required',
            field=models.IntegerField(default=3, verbose_name='연속 달성 횟수 요구'),
        ),
    ]
