# Generated by Django 5.2.4 on 2025-07-30 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_update_growth_models'),
    ]

    operations = [
        # Add missing score fields to ComprehensiveEvaluation
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='contribution_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name='기여도 점수'
            ),
        ),
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='expertise_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name='전문성 점수'
            ),
        ),
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='impact_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name='영향력 점수'
            ),
        ),
        # Add missing achievement fields
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='contribution_achieved',
            field=models.BooleanField(
                default=False,
                verbose_name='기여도 달성'
            ),
        ),
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='expertise_achieved',
            field=models.BooleanField(
                default=False,
                verbose_name='전문성 달성'
            ),
        ),
        migrations.AddField(
            model_name='comprehensiveevaluation',
            name='impact_achieved',
            field=models.BooleanField(
                default=False,
                verbose_name='영향력 달성'
            ),
        ),
    ]
