# Generated by Django 5.2.4 on 2025-08-06 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_auto_20250730_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthlevel',
            name='consecutive_achievements_required',
        ),
        migrations.RemoveField(
            model_name='growthlevel',
            name='min_score_requirement',
        ),
        migrations.AddField(
            model_name='performancetrend',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='현재 레벨'),
        ),
        migrations.AlterField(
            model_name='growthlevel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='레벨 설명'),
        ),
    ]
