# Generated by Django 5.2.4 on 2025-08-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
        ('evaluations', '0006_remove_growthlevel_consecutive_achievements_required_and_more'),
    ]

    operations = [
    ]
