# Generated by Django 5.2.4 on 2025-07-16 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_alter_employee_hire_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_department",
                    models.CharField(max_length=100, verbose_name="이전 부서"),
                ),
                (
                    "to_department",
                    models.CharField(max_length=100, verbose_name="이동 부서"),
                ),
                (
                    "from_position",
                    models.CharField(max_length=100, verbose_name="이전 직책"),
                ),
                (
                    "to_position",
                    models.CharField(max_length=100, verbose_name="이동 직책"),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "승진"),
                            ("LATERAL", "평이동"),
                            ("DEMOTION", "강등"),
                            ("ROTATION", "순환"),
                            ("SPECIAL", "특별이동"),
                        ],
                        max_length=20,
                        verbose_name="이동 유형",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="발령일")),
                ("announcement_date", models.DateField(verbose_name="공고일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "심사대기"),
                            ("UNDER_REVIEW", "심사중"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(blank=True, null=True, verbose_name="승인일"),
                ),
                ("reason", models.TextField(verbose_name="이동 사유")),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="추가 비고"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved",
                        to="employees.employee",
                        verbose_name="승인자",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_transfers",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
            ],
            options={
                "verbose_name": "인사이동",
                "verbose_name_plural": "인사이동",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, unique=True, verbose_name="부서"),
                ),
                (
                    "employee_count",
                    models.IntegerField(default=0, verbose_name="직원 수"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="표시 순서"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to="employees.employee",
                        verbose_name="부서장",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promotions.organizationchart",
                        verbose_name="상위 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "조직도",
                "verbose_name_plural": "조직도",
                "ordering": ["display_order", "department"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="현재 레벨",
                    ),
                ),
                (
                    "target_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="목표 레벨",
                    ),
                ),
                (
                    "evaluation_results",
                    models.JSONField(default=dict, verbose_name="평가 결과"),
                ),
                (
                    "years_of_service",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="재직기간 (년)"
                    ),
                ),
                (
                    "consecutive_a_grades",
                    models.IntegerField(verbose_name="연속 A등급 이상 (회)"),
                ),
                (
                    "average_performance_score",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="평균 성과점수"
                    ),
                ),
                (
                    "years_requirement_met",
                    models.BooleanField(
                        default=False, verbose_name="재직기간 요건 충족"
                    ),
                ),
                (
                    "grades_requirement_met",
                    models.BooleanField(default=False, verbose_name="등급 요건 충족"),
                ),
                (
                    "performance_requirement_met",
                    models.BooleanField(default=False, verbose_name="성과 요건 충족"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "심사대기"),
                            ("UNDER_REVIEW", "심사중"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "department_recommendation",
                    models.BooleanField(default=False, verbose_name="부서장 추천"),
                ),
                (
                    "department_recommendation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="부서장 추천일"
                    ),
                ),
                (
                    "hr_committee_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "심사대기"),
                            ("UNDER_REVIEW", "심사중"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="HR위원회 결정",
                    ),
                ),
                (
                    "hr_committee_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HR위원회 심사일"
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "심사대기"),
                            ("UNDER_REVIEW", "심사중"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="최종 결정",
                    ),
                ),
                (
                    "final_decision_date",
                    models.DateField(blank=True, null=True, verbose_name="최종 결정일"),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, verbose_name="직원 의견"),
                ),
                (
                    "department_comments",
                    models.TextField(blank=True, verbose_name="부서장 의견"),
                ),
                ("hr_comments", models.TextField(blank=True, verbose_name="HR 의견")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department_recommender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_recommended",
                        to="employees.employee",
                        verbose_name="부서장",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="employees.employee",
                        verbose_name="직원",
                    ),
                ),
                (
                    "final_decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_decided",
                        to="employees.employee",
                        verbose_name="최종 결정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "승진 요청",
                "verbose_name_plural": "승진 요청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="현재 레벨",
                    ),
                ),
                (
                    "to_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="목표 레벨",
                    ),
                ),
                (
                    "min_years_required",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        verbose_name="최소 재직기간 (년)",
                    ),
                ),
                (
                    "consecutive_a_grades",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="연속 A등급 이상 (회)",
                    ),
                ),
                (
                    "min_performance_score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="최소 성과점수",
                    ),
                ),
                (
                    "department_recommendation_required",
                    models.BooleanField(default=True, verbose_name="부서장 추천 필수"),
                ),
                (
                    "hr_committee_required",
                    models.BooleanField(
                        default=True, verbose_name="HR위원회 심사 필수"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "승진 요건",
                "verbose_name_plural": "승진 요건",
                "ordering": ["from_level", "to_level"],
                "unique_together": {("from_level", "to_level")},
            },
        ),
    ]
