# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='직위 코드')),
                ('name', models.CharField(max_length=50, verbose_name='직위명')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='직위명(영문)')),
                ('position_type', models.CharField(choices=[('EXECUTIVE', '임원'), ('MANAGEMENT', '관리직'), ('PROFESSIONAL', '전문직'), ('GENERAL', '일반직'), ('TECHNICAL', '기술직'), ('SUPPORT', '지원직')], default='GENERAL', max_length=20, verbose_name='직위 유형')),
                ('rank', models.IntegerField(default=1, help_text='낮을수록 높은 직급', verbose_name='직급 순위')),
                ('growth_level_min', models.IntegerField(default=1, verbose_name='최소 성장레벨')),
                ('growth_level_max', models.IntegerField(default=6, verbose_name='최대 성장레벨')),
                ('is_manager', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('can_approve', models.BooleanField(default=False, verbose_name='결재 권한')),
                ('can_evaluate', models.BooleanField(default=False, verbose_name='평가 권한')),
                ('description', models.TextField(blank=True, verbose_name='직위 설명')),
                ('responsibilities', models.TextField(blank=True, verbose_name='주요 책임')),
                ('requirements', models.TextField(blank=True, verbose_name='자격 요건')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직위',
                'verbose_name_plural': '직위 관리',
                'ordering': ['rank', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='부서 코드')),
                ('name', models.CharField(max_length=100, verbose_name='부서명')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='부서명(영문)')),
                ('level', models.IntegerField(default=1, verbose_name='조직 레벨')),
                ('department_type', models.CharField(choices=[('HQ', '본사'), ('BRANCH', '지점'), ('DIVISION', '사업부'), ('TEAM', '팀'), ('CENTER', '센터'), ('LAB', '연구소')], default='TEAM', max_length=20, verbose_name='부서 유형')),
                ('description', models.TextField(blank=True, verbose_name='부서 설명')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='대표 전화')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='대표 이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='설립일')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='폐쇄일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee', verbose_name='부서장')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.department', verbose_name='상위 부서')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서 관리',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PROMOTION', '승진'), ('TRANSFER', '전보'), ('ASSIGNMENT', '배치'), ('SECONDMENT', '파견'), ('RETURN', '복귀'), ('DEMOTION', '강등')], max_length=20, verbose_name='이동 유형')),
                ('transfer_date', models.DateField(verbose_name='이동일')),
                ('old_position', models.CharField(max_length=50, verbose_name='이전 직위')),
                ('old_growth_level', models.IntegerField(verbose_name='이전 성장레벨')),
                ('new_position', models.CharField(max_length=50, verbose_name='새 직위')),
                ('new_growth_level', models.IntegerField(verbose_name='새 성장레벨')),
                ('reason', models.TextField(verbose_name='이동 사유')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='employees.employee', verbose_name='직원')),
                ('new_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='organization.department', verbose_name='새 부서')),
                ('old_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='organization.department', verbose_name='이전 부서')),
            ],
            options={
                'verbose_name': '인사 이동',
                'verbose_name_plural': '인사 이동 관리',
                'ordering': ['-transfer_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='버전')),
                ('name', models.CharField(max_length=100, verbose_name='조직도명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성 버전')),
                ('effective_date', models.DateField(verbose_name='시행일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_charts', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_charts', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '조직도',
                'verbose_name_plural': '조직도 관리',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATE', '신설'), ('MERGE', '통합'), ('SPLIT', '분할'), ('RENAME', '명칭변경'), ('REORGANIZE', '개편'), ('CLOSE', '폐쇄')], max_length=20, verbose_name='변경 유형')),
                ('old_name', models.CharField(blank=True, max_length=100, verbose_name='이전 명칭')),
                ('new_name', models.CharField(blank=True, max_length=100, verbose_name='새 명칭')),
                ('reason', models.TextField(verbose_name='변경 사유')),
                ('changed_date', models.DateField(verbose_name='변경일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='organization.department', verbose_name='부서')),
                ('new_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_parent_history', to='organization.department', verbose_name='새 상위부서')),
                ('old_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_parent_history', to='organization.department', verbose_name='이전 상위부서')),
                ('organization_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationchart', verbose_name='조직도 버전')),
            ],
            options={
                'verbose_name': '부서 변경 이력',
                'verbose_name_plural': '부서 변경 이력',
                'ordering': ['-changed_date', 'department'],
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='역할')),
                ('is_primary', models.BooleanField(default=True, verbose_name='주 소속')),
                ('assignment_ratio', models.IntegerField(default=100, help_text='해당 팀에서의 업무 비중', verbose_name='업무 비중(%)')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='organization.department', verbose_name='팀/부서')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '팀 배치',
                'verbose_name_plural': '팀 배치 관리',
                'ordering': ['-is_primary', '-assignment_ratio', 'employee'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='organizatio_code_320010_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent', 'level'], name='organizatio_parent__7e9695_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetransfer',
            index=models.Index(fields=['employee', 'transfer_date'], name='organizatio_employe_c71d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetransfer',
            index=models.Index(fields=['transfer_type', 'transfer_date'], name='organizatio_transfe_36b74d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamassignment',
            unique_together={('employee', 'department', 'start_date')},
        ),
    ]
