# Generated by Django 5.2.4 on 2025-08-20 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_enhanced_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgchangelog',
            new_name='organizatio_created_88e0ed_idx',
            old_name='organizatio_created_4e2b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='orgchangelog',
            new_name='organizatio_user_id_e410c6_idx',
            old_name='organizatio_user_id_9a3f7e_idx',
        ),
        migrations.RenameIndex(
            model_name='orgchangelog',
            new_name='organizatio_action_e03ab0_idx',
            old_name='organizatio_action_7c8e4d_idx',
        ),
        migrations.RenameIndex(
            model_name='orgscenario',
            new_name='organizatio_created_938967_idx',
            old_name='organizatio_created_8f3a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='orgscenario',
            new_name='organizatio_author__b32e52_idx',
            old_name='organizatio_author__c7d9f3_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='organizatio_company_115347_idx',
            old_name='organizatio_company_d0f8a9_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='organizatio_reports_ad7156_idx',
            old_name='organizatio_reports_7e6a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='organizatio_functio_8619c7_idx',
            old_name='organizatio_functio_9c3e4d_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='organizatio_company_2fef00_idx',
            old_name='organizatio_company_3b2c8a_idx',
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='headcount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='인원수'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='leader_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)], verbose_name='리더 나이'),
        ),
    ]
