# Generated by Django 5.2.4 on 2025-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("HR", "인사"),
                            ("FINANCE", "재무"),
                            ("MARKETING", "마케팅"),
                            ("SALES", "영업"),
                            ("OPERATIONS", "운영"),
                        ],
                        max_length=20,
                        verbose_name="부서",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("INTERN", "인턴"),
                            ("STAFF", "사원"),
                            ("SENIOR", "대리"),
                            ("MANAGER", "과장"),
                            ("DIRECTOR", "부장"),
                            ("EXECUTIVE", "임원"),
                        ],
                        max_length=20,
                        verbose_name="직급",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="입사일")),
                ("phone", models.CharField(max_length=15, verbose_name="전화번호")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "직원",
                "verbose_name_plural": "직원들",
                "ordering": ["-created_at"],
            },
        ),
    ]
