# Generated by Django 5.2.4 on 2025-07-30 07:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', '인사'), ('FINANCE', '재무'), ('MARKETING', '마케팅'), ('SALES', '영업'), ('OPERATIONS', '운영')], max_length=20, verbose_name='부서')),
                ('position', models.CharField(choices=[('INTERN', '인턴'), ('STAFF', '사원'), ('SENIOR', '대리'), ('MANAGER', '과장'), ('DIRECTOR', '부장'), ('EXECUTIVE', '임원')], max_length=20, verbose_name='직급')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='입사일')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, verbose_name='비상연락처(이름)')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='비상연락처(번호)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('job_group', models.CharField(choices=[('PL', 'PL직군'), ('Non-PL', 'Non-PL직군')], default='Non-PL', help_text='PL직군(고객지원) 또는 Non-PL직군', max_length=20)),
                ('job_type', models.CharField(choices=[('고객지원', '고객지원'), ('IT기획', 'IT기획'), ('IT개발', 'IT개발'), ('IT운영', 'IT운영'), ('경영관리', '경영관리'), ('기업영업', '기업영업'), ('기업금융', '기업금융'), ('리테일금융', '리테일금융'), ('투자금융', '투자금융')], default='경영관리', help_text='세부 직종 분류', max_length=50)),
                ('job_role', models.CharField(blank=True, help_text='구체적인 직무 (예: 수신고객지원, 시스템기획, HRM 등)', max_length=100)),
                ('growth_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=1, help_text='성장레벨 1-6단계')),
                ('new_position', models.CharField(choices=[('사원', '사원'), ('선임', '선임'), ('주임', '주임'), ('대리', '대리'), ('과장', '과장'), ('차장', '차장'), ('부부장', '부부장'), ('부장', '부장'), ('팀장', '팀장'), ('지점장', '지점장'), ('본부장', '본부장')], default='사원', help_text='조직 내 직책', max_length=50)),
                ('grade_level', models.IntegerField(default=1, help_text='급호 (호봉)')),
                ('employment_type', models.CharField(choices=[('정규직', '정규직'), ('계약직', '계약직'), ('파견', '파견'), ('인턴', '인턴')], default='정규직', max_length=20)),
                ('employment_status', models.CharField(choices=[('재직', '재직'), ('휴직', '휴직'), ('퇴직', '퇴직'), ('파견', '파견')], default='재직', max_length=20)),
                ('manager', models.ForeignKey(blank=True, help_text='직속 상사 (평가권자)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원관리',
                'db_table': 'employees_employee',
                'ordering': ['department', 'growth_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HRContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=100, verbose_name='성명')),
                ('vendor_company', models.CharField(max_length=200, verbose_name='소속업체')),
                ('project_name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='투입부서')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당업무')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='투입일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='일단가')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='월단가')),
                ('status', models.CharField(choices=[('active', '진행중'), ('completed', '종료'), ('pending', '예정')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '외주 인력',
                'verbose_name_plural': '외주 인력들',
                'db_table': 'hr_contractors',
                'indexes': [models.Index(fields=['vendor_company'], name='hr_contract_vendor__b40412_idx'), models.Index(fields=['project_name'], name='hr_contract_project_05a6b3_idx'), models.Index(fields=['status'], name='hr_contract_status_fc8cb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HREmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사번')),
                ('name', models.CharField(max_length=100, verbose_name='성명')),
                ('company', models.CharField(max_length=100, verbose_name='회사')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='부서')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직책')),
                ('job_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='직급')),
                ('location_type', models.CharField(choices=[('domestic', '국내'), ('overseas', '해외')], default='domestic', max_length=20, verbose_name='위치 구분')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='국가')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='지점')),
                ('employment_type', models.CharField(choices=[('regular', '정규직'), ('PL', 'PL'), ('Non-PL', 'Non-PL')], default='regular', max_length=20, verbose_name='고용 형태')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='입사일')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('status', models.CharField(choices=[('active', '재직'), ('resigned', '퇴직'), ('new_hire', '신규입사')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'HR 직원',
                'verbose_name_plural': 'HR 직원들',
                'db_table': 'hr_employees',
                'indexes': [models.Index(fields=['name'], name='hr_employee_name_e4a113_idx'), models.Index(fields=['company'], name='hr_employee_company_2a55aa_idx'), models.Index(fields=['status'], name='hr_employee_status_ad4954_idx')],
            },
        ),
        migrations.CreateModel(
            name='HRFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(choices=[('domestic', '국내 인력현황'), ('overseas', '해외 인력현황'), ('contractor', '외주 현황')], max_length=50, verbose_name='파일 유형')),
                ('report_date', models.DateField(verbose_name='보고서 날짜')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('processed_status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('total_records', models.IntegerField(blank=True, null=True, verbose_name='전체 레코드')),
                ('success_records', models.IntegerField(blank=True, null=True, verbose_name='성공 레코드')),
                ('error_records', models.IntegerField(blank=True, null=True, verbose_name='오류 레코드')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='오류 로그')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '파일 업로드 이력',
                'verbose_name_plural': '파일 업로드 이력들',
                'db_table': 'hr_file_uploads',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='HRMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='스냅샷 날짜')),
                ('company', models.CharField(max_length=100, verbose_name='회사')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='부서')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직책')),
                ('job_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='직급')),
                ('location_type', models.CharField(max_length=20, verbose_name='위치 구분')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='국가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='employees.hremployee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '월간 스냅샷',
                'verbose_name_plural': '월간 스냅샷들',
                'db_table': 'hr_monthly_snapshots',
                'indexes': [models.Index(fields=['snapshot_date'], name='hr_monthly__snapsho_14bc80_idx')],
                'unique_together': {('snapshot_date', 'employee')},
            },
        ),
    ]
