# Generated by Django 5.2.4 on 2025-07-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["department", "growth_level", "name"],
                "verbose_name": "직원",
                "verbose_name_plural": "직원관리",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("재직", "재직"),
                    ("휴직", "휴직"),
                    ("퇴직", "퇴직"),
                    ("파견", "파견"),
                ],
                default="재직",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("정규직", "정규직"),
                    ("계약직", "계약직"),
                    ("파견", "파견"),
                    ("인턴", "인턴"),
                ],
                default="정규직",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="grade_level",
            field=models.IntegerField(default=1, help_text="급호 (호봉)"),
        ),
        migrations.AddField(
            model_name="employee",
            name="growth_level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                    (6, "Level 6"),
                ],
                default=1,
                help_text="성장레벨 1-6단계",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_group",
            field=models.CharField(
                choices=[("PL", "PL직군"), ("Non-PL", "Non-PL직군")],
                default="Non-PL",
                help_text="PL직군(고객지원) 또는 Non-PL직군",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_role",
            field=models.CharField(
                blank=True,
                help_text="구체적인 직무 (예: 수신고객지원, 시스템기획, HRM 등)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("고객지원", "고객지원"),
                    ("IT기획", "IT기획"),
                    ("IT개발", "IT개발"),
                    ("IT운영", "IT운영"),
                    ("경영관리", "경영관리"),
                    ("기업영업", "기업영업"),
                    ("기업금융", "기업금융"),
                    ("리테일금융", "리테일금융"),
                    ("투자금융", "투자금융"),
                ],
                default="경영관리",
                help_text="세부 직종 분류",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="직속 상사 (평가권자)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="new_position",
            field=models.CharField(
                choices=[
                    ("사원", "사원"),
                    ("선임", "선임"),
                    ("주임", "주임"),
                    ("대리", "대리"),
                    ("과장", "과장"),
                    ("차장", "차장"),
                    ("부부장", "부부장"),
                    ("부장", "부장"),
                    ("팀장", "팀장"),
                    ("지점장", "지점장"),
                    ("본부장", "본부장"),
                ],
                default="사원",
                help_text="조직 내 직책",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employees_employee",
        ),
    ]
