# Generated by Django 5.2.4 on 2025-08-21 07:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_missing_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(help_text='예: GRP001, COM001, HQ001, DEPT001, TEAM001', max_length=50, unique=True, verbose_name='조직코드')),
                ('org_name', models.CharField(max_length=100, verbose_name='조직명')),
                ('org_level', models.IntegerField(choices=[(1, '그룹'), (2, '계열사'), (3, '본부'), (4, '부'), (5, '팀')], verbose_name='조직레벨')),
                ('full_path', models.CharField(blank=True, help_text='예: OK금융그룹 > OK저축은행 > 디지털본부 > IT개발부 > 개발1팀', max_length=500, verbose_name='전체경로')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='그룹명')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='계열사명')),
                ('headquarters_name', models.CharField(blank=True, max_length=100, verbose_name='본부명')),
                ('department_name', models.CharField(blank=True, max_length=100, verbose_name='부서명')),
                ('team_name', models.CharField(blank=True, max_length=100, verbose_name='팀명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='설립일')),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성'), ('pending', '준비중')], default='active', max_length=20, verbose_name='상태')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_organizations', to='employees.employee', verbose_name='조직장')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.organizationstructure', verbose_name='상위조직')),
            ],
            options={
                'verbose_name': '조직구조',
                'verbose_name_plural': '조직구조',
                'ordering': ['org_level', 'sort_order', 'org_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrganizationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='기본 소속 조직 여부', verbose_name='주소속여부')),
                ('role', models.CharField(blank=True, help_text='해당 조직에서의 역할', max_length=50, verbose_name='역할')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_mappings', to='employees.employee', verbose_name='직원')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='employees.organizationstructure', verbose_name='조직')),
            ],
            options={
                'verbose_name': '직원-조직 매핑',
                'verbose_name_plural': '직원-조직 매핑',
                'ordering': ['-is_primary', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='조직 구조 마스터의 소속 조직', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.organizationstructure', verbose_name='소속조직'),
        ),
        migrations.CreateModel(
            name='OrganizationUploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_path', models.FileField(upload_to='organization_uploads/%Y/%m/', verbose_name='업로드파일')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('total_rows', models.IntegerField(default=0, verbose_name='전체 행수')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='처리된 행수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 건수')),
                ('error_count', models.IntegerField(default=0, verbose_name='오류 건수')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='[{"row": 2, "error": "중복된 조직코드"}]', verbose_name='오류상세')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리완료일시')),
                ('options', models.JSONField(blank=True, default=dict, help_text='{"update_existing": true, "create_missing": true}', verbose_name='처리옵션')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '조직구조 업로드이력',
                'verbose_name_plural': '조직구조 업로드이력',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationstructure',
            index=models.Index(fields=['org_code'], name='employees_o_org_cod_4321ce_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationstructure',
            index=models.Index(fields=['org_level', 'status'], name='employees_o_org_lev_446e46_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationstructure',
            index=models.Index(fields=['parent'], name='employees_o_parent__357d08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeorganizationmapping',
            unique_together={('employee', 'organization', 'is_primary')},
        ),
    ]
