# Generated by Django 5.2.4 on 2025-07-15 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0002_alter_employee_options_employee_employment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(default=datetime.date.today, verbose_name="입사일"),
        ),
    ]
