# Generated by Django 5.2.4 on 2025-08-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_organizationstructure_employeeorganizationmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initial_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='입사시 직급'),
        ),
    ]
