# Generated by Django 5.2.4 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, verbose_name="주소"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="비상연락처(이름)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="비상연락처(번호)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="프로필 사진",
            ),
        ),
    ]
