# Generated by Django 5.2.4 on 2025-07-31 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourcedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='계열사명')),
                ('project_name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('is_resident', models.BooleanField(default=True, verbose_name='상주여부')),
                ('headcount', models.IntegerField(default=0, verbose_name='외주인원 수')),
                ('report_date', models.DateField(verbose_name='기준일')),
                ('base_type', models.CharField(choices=[('week', '전주'), ('month', '전월'), ('year_end', '전년말')], default='week', max_length=20, verbose_name='기준유형')),
                ('previous_headcount', models.IntegerField(default=0, verbose_name='이전 인원수')),
                ('headcount_change', models.IntegerField(default=0, verbose_name='증감 인원')),
                ('change_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='증감율(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '외주인력 현황',
                'verbose_name_plural': '외주인력 현황들',
                'db_table': 'hr_outsourced_staff',
                'indexes': [models.Index(fields=['company_name'], name='hr_outsourc_company_0b77a2_idx'), models.Index(fields=['report_date'], name='hr_outsourc_report__7eb891_idx'), models.Index(fields=['is_resident'], name='hr_outsourc_is_resi_7b0e90_idx')],
                'unique_together': {('company_name', 'project_name', 'report_date')},
            },
        ),
    ]
