# Generated by Django 5.2.4 on 2025-07-31 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_outsourcedstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outsourcedstaff',
            name='hr_outsourc_is_resi_7b0e90_idx',
        ),
        migrations.RemoveField(
            model_name='outsourcedstaff',
            name='is_resident',
        ),
        migrations.AddField(
            model_name='outsourcedstaff',
            name='staff_type',
            field=models.CharField(choices=[('resident', '상주'), ('non_resident', '비상주'), ('project', '프로젝트')], default='resident', max_length=20, verbose_name='인력구분'),
        ),
        migrations.AddIndex(
            model_name='outsourcedstaff',
            index=models.Index(fields=['staff_type'], name='hr_outsourc_staff_t_97860e_idx'),
        ),
    ]
