# Generated by Django 5.2.4 on 2025-07-31 04:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_outsourcedstaff_hr_outsourc_is_resi_7b0e90_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outsourcedstaff',
            unique_together={('company_name', 'project_name', 'report_date', 'staff_type')},
        ),
        migrations.CreateModel(
            name='WeeklyWorkforceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(verbose_name='현재 기준일')),
                ('base_date', models.DateField(verbose_name='비교 기준일')),
                ('base_type', models.CharField(choices=[('week', '전주 대비'), ('month', '전월 대비'), ('year_end', '전년말 대비')], max_length=20, verbose_name='비교 기준')),
                ('company', models.CharField(max_length=100, verbose_name='계열사명')),
                ('job_group', models.CharField(max_length=50, verbose_name='직군')),
                ('grade', models.CharField(max_length=50, verbose_name='직급')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직책')),
                ('contract_type', models.CharField(max_length=50, verbose_name='신분')),
                ('current_headcount', models.IntegerField(verbose_name='현재 인원')),
                ('base_headcount', models.IntegerField(verbose_name='기준 인원')),
                ('change_count', models.IntegerField(verbose_name='증감 인원')),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='증감율(%)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='계산일시')),
            ],
            options={
                'verbose_name': '주간 인력 증감',
                'verbose_name_plural': '주간 인력 증감들',
                'db_table': 'weekly_workforce_change',
                'indexes': [models.Index(fields=['current_date', 'base_type'], name='weekly_work_current_a073a1_idx'), models.Index(fields=['company'], name='weekly_work_company_c6e8d3_idx')],
                'unique_together': {('current_date', 'base_date', 'company', 'job_group', 'grade', 'position', 'contract_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyJoinLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('join', '입사'), ('leave', '퇴사'), ('leave_planned', '퇴사예정')], max_length=20, verbose_name='구분')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('company', models.CharField(max_length=100, verbose_name='계열사명')),
                ('org_unit', models.CharField(max_length=100, verbose_name='소속부서')),
                ('grade', models.CharField(max_length=50, verbose_name='직급')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직책')),
                ('job_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='직군')),
                ('date', models.DateField(verbose_name='일자')),
                ('reason', models.TextField(blank=True, help_text='퇴사 사유 등', null=True, verbose_name='사유')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '주간 입/퇴사자',
                'verbose_name_plural': '주간 입/퇴사자들',
                'db_table': 'weekly_join_leave',
                'indexes': [models.Index(fields=['type', 'date'], name='weekly_join_type_ca979a_idx'), models.Index(fields=['company'], name='weekly_join_company_ce068c_idx'), models.Index(fields=['date'], name='weekly_join_date_779e9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWorkforceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='기준일자')),
                ('company', models.CharField(max_length=100, verbose_name='계열사명')),
                ('job_group', models.CharField(help_text='PL / Non-PL', max_length=50, verbose_name='직군')),
                ('grade', models.CharField(help_text='대리 / 과장 / 차장 / 부장 등', max_length=50, verbose_name='직급')),
                ('position', models.CharField(blank=True, help_text='팀장 / 매니저 등', max_length=50, null=True, verbose_name='직책')),
                ('contract_type', models.CharField(help_text='별정직, 전문계약직, 인턴/계약직, 외주인력 등', max_length=50, verbose_name='신분')),
                ('headcount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='인원수')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '주간 인력현황 스냅샷',
                'verbose_name_plural': '주간 인력현황 스냅샷들',
                'db_table': 'weekly_workforce_snapshot',
                'indexes': [models.Index(fields=['snapshot_date'], name='weekly_work_snapsho_404fac_idx'), models.Index(fields=['company'], name='weekly_work_company_fd1da6_idx'), models.Index(fields=['job_group'], name='weekly_work_job_gro_499c0d_idx'), models.Index(fields=['contract_type'], name='weekly_work_contrac_02e0f5_idx')],
                'unique_together': {('snapshot_date', 'company', 'job_group', 'grade', 'position', 'contract_type')},
            },
        ),
    ]
