# Generated by Django 5.2.4 on 2025-07-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_outsourcedstaff_unique_together_and_more'),
    ]

    operations = [
    ]
