# Generated by Django 5.2.4 on 2025-08-01 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_add_weekly_workforce_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasWorkforce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.CharField(choices=[('OK Bank (인니)', 'OK Bank (인니)'), ('OK Asset (인니)', 'OK Asset (인니)'), ('PPCBank (캄보디아)', 'PPCBank (캄보디아)'), ('천진법인 (중국)', '천진법인 (중국)')], max_length=100, verbose_name='법인')),
                ('report_date', models.DateField(verbose_name='기준일')),
                ('executive_count', models.IntegerField(default=0, verbose_name='이사')),
                ('general_manager_count', models.IntegerField(default=0, verbose_name='부장급')),
                ('deputy_manager_count', models.IntegerField(default=0, verbose_name='차장')),
                ('manager_count', models.IntegerField(default=0, verbose_name='과장')),
                ('assistant_manager_count', models.IntegerField(default=0, verbose_name='대리')),
                ('staff_count', models.IntegerField(default=0, verbose_name='사원')),
                ('ceo_count', models.IntegerField(default=0, verbose_name='대표이사')),
                ('division_head_count', models.IntegerField(default=0, verbose_name='본부장')),
                ('department_head_count', models.IntegerField(default=0, verbose_name='부서장')),
                ('branch_manager_count', models.IntegerField(default=0, verbose_name='지점장/Br.Mg')),
                ('team_leader_count', models.IntegerField(default=0, verbose_name='팀장/T.leader/Staff')),
                ('cbo_count', models.IntegerField(default=0, verbose_name='최고사업책임자')),
                ('evp_count', models.IntegerField(default=0, verbose_name='부문장/수석부사장')),
                ('svp_count', models.IntegerField(default=0, verbose_name='상무이사/수석부사장')),
                ('vp_count', models.IntegerField(default=0, verbose_name='상무이사')),
                ('total_count', models.IntegerField(default=0, verbose_name='합계')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '해외 인력 현황',
                'verbose_name_plural': '해외 인력 현황들',
                'db_table': 'hr_overseas_workforce',
                'indexes': [models.Index(fields=['corporation'], name='hr_overseas_corpora_c489bf_idx'), models.Index(fields=['report_date'], name='hr_overseas_report__f5d740_idx')],
                'unique_together': {('corporation', 'report_date')},
            },
        ),
    ]
