# Generated by Django 5.2.4 on 2025-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_overseasworkforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseasworkforce',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='원본 데이터'),
        ),
    ]
