# Generated by Django 5.2.4 on 2025-08-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_options_employee_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dummy_ssn',
        ),
    ]
