# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('job_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='이름')),
                ('last_name', models.CharField(max_length=50, verbose_name='성')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1, null=True, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='포트폴리오 URL')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', verbose_name='이력서 파일')),
                ('cover_letter', models.TextField(blank=True, verbose_name='자기소개서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '지원자',
                'verbose_name_plural': '지원자',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='단계명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '채용 단계',
                'verbose_name_plural': '채용 단계',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', '접수'), ('reviewing', '검토중'), ('interview_scheduled', '면접예정'), ('interviewed', '면접완료'), ('offer_made', '합격'), ('rejected', '불합격'), ('withdrawn', '지원취소')], default='submitted', max_length=20, verbose_name='상태')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='지원일')),
                ('technical_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='기술 점수')),
                ('cultural_fit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='조직 적합도')),
                ('overall_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='종합 평가')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='불합격 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.applicant', verbose_name='지원자')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '지원서',
                'verbose_name_plural': '지원서',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('phone', '전화 면접'), ('video', '화상 면접'), ('onsite', '대면 면접'), ('technical', '기술 면접'), ('hr', '인사 면접'), ('final', '최종 면접')], max_length=20, verbose_name='면접 유형')),
                ('scheduled_date', models.DateTimeField(verbose_name='면접 일시')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='소요 시간(분)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('meeting_link', models.URLField(blank=True, verbose_name='미팅 링크')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('cancelled', '취소'), ('rescheduled', '일정변경')], default='scheduled', max_length=20, verbose_name='상태')),
                ('interview_notes', models.TextField(blank=True, verbose_name='면접 내용')),
                ('technical_assessment', models.TextField(blank=True, verbose_name='기술 평가')),
                ('cultural_assessment', models.TextField(blank=True, verbose_name='인성 평가')),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', '적극 추천'), ('yes', '추천'), ('neutral', '보통'), ('no', '비추천'), ('strong_no', '적극 비추천')], max_length=20, verbose_name='추천 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application', verbose_name='지원서')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL, verbose_name='일정 생성자')),
                ('interviewers', models.ManyToManyField(related_name='interviews_conducted', to='employees.employee', verbose_name='면접관')),
            ],
            options={
                'verbose_name': '면접 일정',
                'verbose_name_plural': '면접 일정',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('position', models.CharField(choices=[('INTERN', '인턴'), ('STAFF', '사원'), ('SENIOR', '대리'), ('MANAGER', '과장'), ('DIRECTOR', '부장'), ('EXECUTIVE', '임원')], max_length=20, verbose_name='채용 직급')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', '인사'), ('FINANCE', '재무'), ('MARKETING', '마케팅'), ('SALES', '영업'), ('OPERATIONS', '운영')], max_length=20, verbose_name='채용 부서')),
                ('employment_type', models.CharField(choices=[('permanent', '정규직'), ('contract', '계약직'), ('intern', '인턴'), ('parttime', '파트타임')], max_length=20, verbose_name='고용 형태')),
                ('description', models.TextField(verbose_name='직무 설명')),
                ('requirements', models.TextField(verbose_name='자격 요건')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대 사항')),
                ('min_experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='최소 경력 연수')),
                ('max_experience_years', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='최대 경력 연수')),
                ('vacancies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='채용 인원')),
                ('location', models.CharField(max_length=100, verbose_name='근무 지역')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='최소 급여')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='최대 급여')),
                ('posted_date', models.DateTimeField(blank=True, null=True, verbose_name='공고 게시일')),
                ('closing_date', models.DateTimeField(verbose_name='마감일')),
                ('status', models.CharField(choices=[('draft', '초안'), ('open', '진행중'), ('closed', '마감'), ('cancelled', '취소')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_profiles.jobrole', verbose_name='직무')),
            ],
            options={
                'verbose_name': '채용공고',
                'verbose_name_plural': '채용공고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting', verbose_name='채용공고'),
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='recruitment.application', verbose_name='지원서')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.recruitmentstage', verbose_name='단계')),
            ],
            options={
                'verbose_name': '지원서 이력',
                'verbose_name_plural': '지원서 이력',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.recruitmentstage', verbose_name='현재 단계'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_posting', 'applicant')},
        ),
    ]
