# Generated by Django 5.2.4 on 2025-07-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecompensation",
            name="pi_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="성과급 (원)"
            ),
        ),
    ]
