# Generated by Django 5.2.4 on 2025-07-16 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0002_alter_employeecompensation_pi_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performanceincentiverate",
            options={
                "ordering": ["growth_level", "-incentive_rate"],
                "verbose_name": "성과급 지급률",
                "verbose_name_plural": "성과급 지급률",
            },
        ),
        migrations.AddField(
            model_name="performanceincentiverate",
            name="growth_level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="성장레벨",
            ),
        ),
        migrations.AlterField(
            model_name="performanceincentiverate",
            name="evaluation_grade",
            field=models.CharField(
                choices=[
                    ("S", "S등급"),
                    ("A+", "A+등급"),
                    ("A", "A등급"),
                    ("B+", "B+등급"),
                    ("B", "B등급"),
                    ("C", "C등급"),
                    ("D", "D등급"),
                ],
                max_length=5,
                verbose_name="평가등급",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performanceincentiverate",
            unique_together={("growth_level", "evaluation_grade")},
        ),
    ]
