# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='직군명')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='직군코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직군',
                'verbose_name_plural': '직군',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='직무명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='직무코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직무',
                'verbose_name_plural': '직무',
                'ordering': ['job_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_responsibility', models.TextField(verbose_name='역할과 책임')),
                ('qualification', models.TextField(verbose_name='자격요건')),
                ('basic_skills', models.JSONField(default=list, verbose_name='기본 기술/지식')),
                ('applied_skills', models.JSONField(default=list, verbose_name='응용 기술/지식')),
                ('growth_path', models.TextField(blank=True, verbose_name='성장경로')),
                ('related_certifications', models.JSONField(default=list, verbose_name='관련 자격증')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='job_profiles.jobrole', verbose_name='직무')),
            ],
            options={
                'verbose_name': '직무기술서',
                'verbose_name_plural': '직무기술서',
                'ordering': ['job_role__job_type__category', 'job_role__job_type', 'job_role'],
            },
        ),
        migrations.CreateModel(
            name='JobProfileHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_data', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, verbose_name='변경 사유')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='job_profiles.jobprofile')),
            ],
            options={
                'verbose_name': '직무기술서 변경이력',
                'verbose_name_plural': '직무기술서 변경이력',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='직종명')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='직종코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='job_profiles.jobcategory', verbose_name='직군')),
            ],
            options={
                'verbose_name': '직종',
                'verbose_name_plural': '직종',
                'ordering': ['category', 'code'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='jobrole',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='job_profiles.jobtype', verbose_name='직종'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrole',
            unique_together={('job_type', 'name')},
        ),
    ]
