# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('changes', models.JSONField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HRRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HR_ADMIN', 'HR 관리자'), ('HR_MANAGER', 'HR 매니저'), ('DEPT_HEAD', '부서장'), ('TEAM_LEADER', '팀장'), ('EMPLOYEE', '일반 직원'), ('EXECUTIVE', '임원')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name': 'HR 역할',
                'verbose_name_plural': 'HR 역할',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.hrrole')),
            ],
            options={
                'verbose_name': '직원 역할',
                'verbose_name_plural': '직원 역할',
                'unique_together': {('employee', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DataAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('SELF', '본인 데이터만'), ('TEAM', '팀 데이터'), ('DEPT', '부서 데이터'), ('COMPANY', '전사 데이터')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.hrrole')),
            ],
            options={
                'verbose_name': '데이터 접근 규칙',
                'verbose_name_plural': '데이터 접근 규칙',
                'unique_together': {('role', 'model_name')},
            },
        ),
    ]
