# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('EMPLOYEE_LIST', '직원 명부'), ('EVALUATION_SUMMARY', '평가 결과 요약'), ('COMPENSATION_ANALYSIS', '보상 분석'), ('PROMOTION_CANDIDATES', '승진 대상자'), ('DEPARTMENT_STATISTICS', '부서별 통계'), ('ANNUAL_HR_REPORT', '연간 HR 리포트')], max_length=50)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters_used', models.JSONField()),
                ('record_count', models.IntegerField()),
                ('file_format', models.CharField(max_length=10)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
        ),
    ]
