# Generated by Django 5.2.4 on 2025-08-18 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type_code', models.CharField(choices=[('TURNOVER_RISK', '퇴사 위험도 예측'), ('PROMOTION_POTENTIAL', '승진 가능성 분석'), ('TEAM_PERFORMANCE', '팀 성과 예측'), ('TALENT_RECOMMENDATION', '인재 추천'), ('COMPENSATION_OPTIMIZATION', '급여 최적화'), ('SKILL_GAP_ANALYSIS', '역량 격차 분석'), ('CAREER_PATH', '경력 경로 추천'), ('ENGAGEMENT_PREDICTION', '직원 참여도 예측')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI 분석 유형',
                'verbose_name_plural': 'AI 분석 유형',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('RETENTION', '인재 유지'), ('PERFORMANCE', '성과 관리'), ('DEVELOPMENT', '인재 개발'), ('COMPENSATION', '보상 관리'), ('ENGAGEMENT', '직원 참여'), ('DIVERSITY', '다양성 및 포용성')], max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '중간'), ('LOW', '낮음')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('impact_analysis', models.TextField(help_text='예상 영향 분석')),
                ('action_items', models.JSONField(default=list, help_text='권장 조치 사항')),
                ('target_departments', models.JSONField(blank=True, default=list, help_text='대상 부서 리스트')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('actions_taken', models.JSONField(default=list)),
                ('target_employees', models.ManyToManyField(blank=True, to='employees.employee')),
            ],
            options={
                'verbose_name': 'AI 인사이트',
                'verbose_name_plural': 'AI 인사이트',
                'ordering': ['-generated_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('parameters', models.JSONField(default=dict, help_text='모델 파라미터')),
                ('thresholds', models.JSONField(default=dict, help_text='임계값 설정')),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(blank=True, help_text='모델 정확도', null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airiss.aianalysistype')),
            ],
            options={
                'verbose_name': 'AI 모델 설정',
                'verbose_name_plural': 'AI 모델 설정',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='HRChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, help_text='대화 메시지 리스트')),
                ('context', models.JSONField(default=dict, help_text='대화 컨텍스트')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='만족도 (1-5)', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR 챗봇 대화',
                'verbose_name_plural': 'HR 챗봇 대화',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, help_text='부서명', max_length=20, null=True)),
                ('score', models.FloatField(help_text='예측 점수 (0-100)')),
                ('confidence', models.FloatField(help_text='신뢰도 (0-1)')),
                ('result_data', models.JSONField(default=dict, help_text='상세 분석 결과')),
                ('recommendations', models.JSONField(default=list, help_text='추천 사항')),
                ('insights', models.TextField(blank=True, help_text='주요 인사이트')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airiss.aianalysistype')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['analysis_type', 'employee'], name='airiss_aian_analysi_37c843_idx'), models.Index(fields=['analyzed_at'], name='airiss_aian_analyze_5440d3_idx')],
            },
        ),
    ]
