# Generated by Django 5.2.4 on 2025-07-24 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '교육 카테고리',
                'verbose_name_plural': '교육 카테고리',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50, unique=True, verbose_name='과정코드')),
                ('title', models.CharField(max_length=200, verbose_name='과정명')),
                ('description', models.TextField(verbose_name='과정 설명')),
                ('objectives', models.JSONField(default=list, verbose_name='학습목표')),
                ('target_audience', models.TextField(blank=True, verbose_name='대상자')),
                ('related_skills', models.JSONField(default=list, verbose_name='관련 스킬')),
                ('skill_level', models.CharField(choices=[('BASIC', '기초'), ('INTERMEDIATE', '중급'), ('ADVANCED', '고급'), ('EXPERT', '전문가')], default='INTERMEDIATE', max_length=20, verbose_name='스킬 수준')),
                ('duration_hours', models.IntegerField(default=8, verbose_name='교육시간')),
                ('course_type', models.CharField(choices=[('ONLINE', '온라인'), ('OFFLINE', '오프라인'), ('BLENDED', '혼합형'), ('SELF_STUDY', '자율학습')], default='ONLINE', max_length=20, verbose_name='교육유형')),
                ('min_growth_level', models.CharField(blank=True, max_length=10, verbose_name='최소 성장레벨')),
                ('certification_eligible', models.BooleanField(default=False, verbose_name='인증교육여부')),
                ('growth_level_impact', models.JSONField(default=dict, help_text='예: {"Lv.3": 0.2, "Lv.4": 0.1}', verbose_name='성장레벨 영향')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='교육제공처')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='비용')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='필수교육여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.trainingcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '교육과정',
                'verbose_name_plural': '교육과정',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillTrainingMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='스킬명')),
                ('skill_category', models.CharField(max_length=50, verbose_name='스킬카테고리')),
                ('relevance_score', models.FloatField(default=1.0, verbose_name='관련도점수')),
                ('is_core_skill', models.BooleanField(default=False, verbose_name='핵심스킬여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(to='trainings.trainingcourse', verbose_name='관련교육')),
            ],
            options={
                'verbose_name': '스킬-교육 매핑',
                'verbose_name_plural': '스킬-교육 매핑',
                'ordering': ['skill_category', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_job', models.CharField(max_length=100, verbose_name='목표직무')),
                ('missing_skills', models.JSONField(default=list, verbose_name='부족스킬')),
                ('match_score', models.FloatField(verbose_name='매치점수')),
                ('priority', models.IntegerField(verbose_name='우선순위')),
                ('recommendation_type', models.CharField(choices=[('SKILL_GAP', '스킬갭 해소'), ('GROWTH_LEVEL', '성장레벨 향상'), ('MANDATORY', '필수교육'), ('CAREER_PATH', '경력개발'), ('PERFORMANCE', '성과향상')], max_length=30, verbose_name='추천유형')),
                ('recommendation_comment', models.TextField(verbose_name='추천코멘트')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='수강신청여부')),
                ('enrolled_date', models.DateTimeField(blank=True, null=True, verbose_name='신청일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추천일')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingcourse', verbose_name='교육과정')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '교육추천',
                'verbose_name_plural': '교육추천',
                'ordering': ['-created_at', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('APPLIED', '신청'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('IN_PROGRESS', '수강중'), ('COMPLETED', '이수'), ('INCOMPLETE', '미이수'), ('CANCELLED', '취소')], default='APPLIED', max_length=20, verbose_name='상태')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='수강시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='수강종료일')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='이수일')),
                ('attendance_rate', models.FloatField(default=0, verbose_name='출석률')),
                ('test_score', models.FloatField(blank=True, null=True, verbose_name='평가점수')),
                ('satisfaction_score', models.IntegerField(blank=True, null=True, verbose_name='만족도')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='추천사유')),
                ('recommendation_priority', models.IntegerField(default=50, verbose_name='추천우선순위')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingcourse', verbose_name='교육과정')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '교육수강',
                'verbose_name_plural': '교육수강',
                'ordering': ['-enrolled_date'],
                'unique_together': {('employee', 'course', 'start_date')},
            },
        ),
    ]
