# Generated by Django 5.2.4 on 2025-07-24 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_user'),
        ('job_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='예: Lv.1, Lv.2, Lv.3, Lv.4, Lv.5', max_length=10, unique=True, verbose_name='성장레벨')),
                ('level_name', models.CharField(max_length=50, verbose_name='레벨명')),
                ('min_evaluation_grade', models.CharField(help_text='예: B+, A, A+, S', max_length=10, verbose_name='최소 평가등급')),
                ('consecutive_evaluations', models.IntegerField(default=1, help_text='최소 등급 이상을 받아야 하는 연속 평가 횟수', verbose_name='연속 평가 횟수')),
                ('required_courses', models.JSONField(default=list, help_text='과정 코드 리스트', verbose_name='필수 교육과정')),
                ('required_course_categories', models.JSONField(default=dict, help_text='예: {"리더십": 2, "직무역량": 3}', verbose_name='카테고리별 필수 교육 수')),
                ('min_training_hours', models.IntegerField(default=0, verbose_name='최소 교육시간')),
                ('required_skills', models.JSONField(default=list, help_text='스킬 리스트', verbose_name='필수 스킬')),
                ('skill_proficiency_level', models.CharField(choices=[('BASIC', '기초'), ('INTERMEDIATE', '중급'), ('ADVANCED', '고급'), ('EXPERT', '전문가')], default='INTERMEDIATE', max_length=20, verbose_name='스킬 숙련도')),
                ('min_years_in_level', models.FloatField(default=0, verbose_name='현 레벨 최소 경력(년)')),
                ('min_total_years', models.FloatField(default=0, verbose_name='총 경력 최소(년)')),
                ('additional_requirements', models.JSONField(default=dict, help_text='기타 특수 요건', verbose_name='추가 요건')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '성장레벨 요건',
                'verbose_name_plural': '성장레벨 요건',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CertificationCheckLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_level', models.CharField(max_length=10, verbose_name='목표레벨')),
                ('target_job', models.CharField(blank=True, max_length=100, verbose_name='목표직무')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='체크시점')),
                ('check_result', models.CharField(choices=[('READY', '인증가능'), ('NOT_READY', '미충족'), ('PARTIAL', '부분충족')], max_length=20, verbose_name='체크결과')),
                ('result_details', models.JSONField(default=dict, help_text='각 요건별 충족 여부 및 부족 사항', verbose_name='결과상세')),
                ('expected_certification_date', models.DateField(blank=True, null=True, verbose_name='예상인증일')),
                ('api_source', models.CharField(blank=True, help_text='어떤 API에서 호출되었는지', max_length=50, verbose_name='API출처')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '인증체크로그',
                'verbose_name_plural': '인증체크로그',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthLevelCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('growth_level', models.CharField(max_length=10, verbose_name='인증레벨')),
                ('status', models.CharField(choices=[('PENDING', '검토중'), ('CERTIFIED', '인증완료'), ('REJECTED', '반려'), ('EXPIRED', '만료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('certified_date', models.DateTimeField(blank=True, null=True, verbose_name='인증일')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('certification_snapshot', models.JSONField(default=dict, help_text='인증 당시의 평가, 교육, 스킬 정보', verbose_name='인증시점 데이터')),
                ('evaluation_check', models.BooleanField(default=False, verbose_name='평가요건충족')),
                ('training_check', models.BooleanField(default=False, verbose_name='교육요건충족')),
                ('skill_check', models.BooleanField(default=False, verbose_name='스킬요건충족')),
                ('experience_check', models.BooleanField(default=False, verbose_name='경력요건충족')),
                ('missing_requirements', models.JSONField(default=dict, help_text='부족한 요건 상세', verbose_name='미충족 요건')),
                ('review_notes', models.TextField(blank=True, verbose_name='검토의견')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='직원')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '성장레벨 인증',
                'verbose_name_plural': '성장레벨 인증',
                'ordering': ['-applied_date'],
                'unique_together': {('employee', 'growth_level', 'status')},
            },
        ),
        migrations.CreateModel(
            name='JobLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_growth_level', models.CharField(max_length=10, verbose_name='필수 성장레벨')),
                ('job_specific_courses', models.JSONField(default=list, help_text='해당 직무에만 필요한 추가 교육', verbose_name='직무별 필수 교육')),
                ('job_specific_skills', models.JSONField(default=list, help_text='해당 직무에만 필요한 추가 스킬', verbose_name='직무별 필수 스킬')),
                ('override_eval_grade', models.CharField(blank=True, help_text='비어있으면 레벨 기본값 사용', max_length=10, verbose_name='평가등급 오버라이드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile', verbose_name='직무프로파일')),
            ],
            options={
                'verbose_name': '직무별 레벨 요건',
                'verbose_name_plural': '직무별 레벨 요건',
                'unique_together': {('job_profile', 'required_growth_level')},
            },
        ),
    ]
