# Generated by Django 5.2.4 on 2025-07-29 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True, verbose_name='검색어')),
                ('search_count', models.IntegerField(default=0, verbose_name='검색 횟수')),
                ('daily_count', models.IntegerField(default=0, verbose_name='일일 검색 수')),
                ('weekly_count', models.IntegerField(default=0, verbose_name='주간 검색 수')),
                ('monthly_count', models.IntegerField(default=0, verbose_name='월간 검색 수')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='마지막 검색일')),
                ('trend_score', models.FloatField(default=0.0, verbose_name='트렌드 스코어')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '인기 검색어',
                'verbose_name_plural': '인기 검색어 관리',
                'ordering': ['-trend_score', '-search_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='제안 검색어')),
                ('display_text', models.CharField(max_length=500, verbose_name='표시 텍스트')),
                ('suggestion_type', models.CharField(choices=[('QUERY', '검색어'), ('EMPLOYEE', '직원명'), ('DEPARTMENT', '부서명'), ('POSITION', '직위명'), ('KEYWORD', '키워드')], default='QUERY', max_length=20, verbose_name='제안 유형')),
                ('priority', models.IntegerField(default=1, verbose_name='우선순위')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '검색 제안',
                'verbose_name_plural': '검색 제안 관리',
                'ordering': ['-priority', '-usage_count'],
                'unique_together': {('query', 'suggestion_type')},
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='검색명')),
                ('query', models.CharField(max_length=500, verbose_name='검색어')),
                ('search_type', models.CharField(blank=True, choices=[('EMPLOYEE', '직원'), ('DEPARTMENT', '부서'), ('POSITION', '직위'), ('ANNOUNCEMENT', '공지사항'), ('EVALUATION', '평가'), ('TRAINING', '교육'), ('JOB_PROFILE', '직무'), ('RECRUITMENT', '채용')], max_length=20, verbose_name='검색 분류')),
                ('enable_alerts', models.BooleanField(default=False, verbose_name='새 결과 알림')),
                ('alert_frequency', models.CharField(choices=[('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월')], default='WEEKLY', max_length=10, verbose_name='알림 주기')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True, verbose_name='마지막 알림 발송일')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='employees.employee', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '저장된 검색',
                'verbose_name_plural': '저장된 검색 관리',
                'ordering': ['-last_used', '-usage_count'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=100)),
                ('search_type', models.CharField(choices=[('EMPLOYEE', '직원'), ('DEPARTMENT', '부서'), ('POSITION', '직위'), ('ANNOUNCEMENT', '공지사항'), ('EVALUATION', '평가'), ('TRAINING', '교육'), ('JOB_PROFILE', '직무'), ('RECRUITMENT', '채용')], max_length=20, verbose_name='검색 분류')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('keywords', models.TextField(blank=True, help_text='검색용 키워드 (공백으로 구분)', verbose_name='키워드')),
                ('url', models.URLField(blank=True, verbose_name='링크 URL')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('department_restricted', models.CharField(blank=True, help_text='특정 부서만 검색 가능', max_length=20, verbose_name='부서 제한')),
                ('position_restricted', models.CharField(blank=True, help_text='특정 직위 이상만 검색 가능', max_length=50, verbose_name='직위 제한')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('search_count', models.IntegerField(default=0, verbose_name='검색 횟수')),
                ('last_searched', models.DateTimeField(blank=True, null=True, verbose_name='마지막 검색일')),
                ('priority', models.IntegerField(default=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '검색 인덱스',
                'verbose_name_plural': '검색 인덱스 관리',
                'ordering': ['-priority', '-updated_at'],
                'indexes': [models.Index(fields=['search_type', 'is_public'], name='search_sear_search__179c9d_idx'), models.Index(fields=['title'], name='search_sear_title_51a3a1_idx'), models.Index(fields=['content'], name='search_sear_content_a80c07_idx'), models.Index(fields=['keywords'], name='search_sear_keyword_974af2_idx'), models.Index(fields=['search_count', 'last_searched'], name='search_sear_search__e91ac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500, verbose_name='검색어')),
                ('query_normalized', models.CharField(help_text='공백 제거, 소문자 변환 등', max_length=500, verbose_name='정규화된 검색어')),
                ('search_type', models.CharField(blank=True, choices=[('EMPLOYEE', '직원'), ('DEPARTMENT', '부서'), ('POSITION', '직위'), ('ANNOUNCEMENT', '공지사항'), ('EVALUATION', '평가'), ('TRAINING', '교육'), ('JOB_PROFILE', '직무'), ('RECRUITMENT', '채용')], max_length=20, verbose_name='검색 분류')),
                ('results_count', models.IntegerField(default=0, verbose_name='결과 수')),
                ('selected_result_id', models.UUIDField(blank=True, null=True, verbose_name='선택한 결과 ID')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='실행 시간(초)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='employees.employee', verbose_name='검색자')),
            ],
            options={
                'verbose_name': '검색 로그',
                'verbose_name_plural': '검색 로그 관리',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_sear_user_id_2836be_idx'), models.Index(fields=['query', 'created_at'], name='search_sear_query_62def4_idx'), models.Index(fields=['search_type', 'created_at'], name='search_sear_search__14ceec_idx')],
            },
        ),
    ]
