# Generated by Django 5.2.4 on 2025-08-07 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0013_remove_employee_dummy_ssn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('total_employees', models.IntegerField(default=0, verbose_name='총 직원수')),
                ('new_hires', models.IntegerField(default=0, verbose_name='신규 입사')),
                ('resignations', models.IntegerField(default=0, verbose_name='퇴사')),
                ('avg_performance_score', models.FloatField(default=0.0, verbose_name='평균 성과 점수')),
                ('high_performers_count', models.IntegerField(default=0, verbose_name='고성과자 수')),
                ('low_performers_count', models.IntegerField(default=0, verbose_name='저성과자 수')),
                ('avg_engagement_score', models.FloatField(default=0.0, verbose_name='평균 몰입도')),
                ('burnout_risk_count', models.IntegerField(default=0, verbose_name='번아웃 위험 인원')),
                ('avg_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='평균 보상')),
                ('compensation_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='보상 예산 사용률')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('ai_predictions', models.JSONField(default=dict, verbose_name='AI 예측')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '일일 메트릭',
                'verbose_name_plural': '일일 메트릭',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.CharField(choices=[('TURNOVER', '이직 위험'), ('PERFORMANCE', '성과'), ('ENGAGEMENT', '몰입도'), ('COMPENSATION', '보상'), ('TEAM', '팀 역학'), ('LEADERSHIP', '리더십')], max_length=20, verbose_name='카테고리')),
                ('priority', models.CharField(choices=[('URGENT', '긴급'), ('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('affected_department', models.CharField(blank=True, max_length=100, verbose_name='영향받는 부서')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='AI 신뢰도')),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=50, verbose_name='사용된 AI 모델')),
                ('raw_analysis', models.JSONField(default=dict, verbose_name='원본 분석 데이터')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='추천 액션')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결일시')),
                ('affected_employees', models.ManyToManyField(blank=True, related_name='affected_by_insights', to='employees.employee', verbose_name='영향받는 직원')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='해결자')),
            ],
            options={
                'verbose_name': 'AI 인사이트',
                'verbose_name_plural': 'AI 인사이트',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('priority', models.CharField(choices=[('URGENT', '긴급'), ('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='상태')),
                ('target_department', models.CharField(blank=True, max_length=100, verbose_name='대상 부서')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('expected_impact', models.TextField(blank=True, verbose_name='예상 효과')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='AI 신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_actions', to='employees.employee', verbose_name='대상 직원')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='ai_insights.aiinsight', verbose_name='관련 인사이트')),
            ],
            options={
                'verbose_name': '액션 아이템',
                'verbose_name_plural': '액션 아이템',
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
