# Generated by Django 5.2.4 on 2025-08-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_submitted', 'Evaluation Submitted'), ('evaluation_approved', 'Evaluation Approved'), ('evaluation_rejected', 'Evaluation Rejected'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('feedback_received', 'Feedback Received'), ('goal_updated', 'Goal Updated'), ('deadline_reminder', 'Deadline Reminder'), ('system', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
