# Generated by Django 5.2.4 on 2025-07-29 01:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='알림 유형명')),
                ('category', models.CharField(choices=[('HR', 'HR 관련'), ('SYSTEM', '시스템'), ('WORKFLOW', '업무 프로세스'), ('EVALUATION', '평가'), ('TRAINING', '교육'), ('ANNOUNCEMENT', '공지사항')], default='SYSTEM', max_length=20, verbose_name='카테고리')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('NORMAL', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='NORMAL', max_length=10, verbose_name='우선순위')),
                ('template', models.TextField(verbose_name='메시지 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('auto_expire_days', models.IntegerField(default=30, help_text='일 단위, 0이면 만료되지 않음', verbose_name='자동 만료일')),
                ('send_email', models.BooleanField(default=False, verbose_name='이메일 발송')),
                ('send_sms', models.BooleanField(default=False, verbose_name='SMS 발송')),
                ('send_push', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '알림 유형',
                'verbose_name_plural': '알림 유형 관리',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('visibility', models.CharField(choices=[('ALL', '전체'), ('DEPARTMENT', '부서'), ('POSITION', '직위'), ('CUSTOM', '선택')], default='ALL', max_length=20, verbose_name='공개 범위')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요 공지')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='긴급 공지')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시일')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 상태')),
                ('attachment', models.FileField(blank=True, upload_to='announcements/', verbose_name='첨부파일')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='employees.employee', verbose_name='작성자')),
                ('target_departments', models.ManyToManyField(blank=True, to='organization.department', verbose_name='대상 부서')),
                ('target_employees', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='대상 직원')),
                ('target_positions', models.ManyToManyField(blank=True, to='organization.position', verbose_name='대상 직위')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 관리',
                'ordering': ['-is_important', '-is_urgent', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('data', models.JSONField(blank=True, default=dict, help_text='관련 객체 ID, URL 등', verbose_name='추가 데이터')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SENT', '발송완료'), ('READ', '읽음'), ('EXPIRED', '만료'), ('FAILED', '실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 발송 시간')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시간')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시간')),
                ('action_url', models.URLField(blank=True, help_text='클릭시 이동할 URL', verbose_name='액션 URL')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='액션 버튼 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='employees.employee', verbose_name='수신자')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='employees.employee', verbose_name='발신자')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype', verbose_name='알림 유형')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PUSH', '푸시'), ('EMAIL', '이메일'), ('SMS', 'SMS')], max_length=10, verbose_name='발송 채널')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], max_length=10, verbose_name='발송 상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시간')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='알림')),
            ],
            options={
                'verbose_name': '알림 로그',
                'verbose_name_plural': '알림 로그',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='알림 활성화')),
                ('enable_email', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='SMS 알림')),
                ('enable_push', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('hr_notifications', models.BooleanField(default=True, verbose_name='HR 알림')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='시스템 알림')),
                ('workflow_notifications', models.BooleanField(default=True, verbose_name='업무 알림')),
                ('evaluation_notifications', models.BooleanField(default=True, verbose_name='평가 알림')),
                ('training_notifications', models.BooleanField(default=True, verbose_name='교육 알림')),
                ('announcement_notifications', models.BooleanField(default=True, verbose_name='공지 알림')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='방해금지 시작시간')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='방해금지 종료시간')),
                ('weekend_notifications', models.BooleanField(default=False, verbose_name='주말 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정 관리',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_5e6e57_idx'),
        ),
    ]
